### ISSUE TITLE
after rebuild => SOLR schema version not supported: 2.8. Supported versions are [2.7]

### ISSUE THREAD

**Issue by terchris** [okfn/docker-ckan#20]
Hi
I did a "docker-compose build --no-cache". It seems that there has been a change in the SOLR schema. This is my output:
ckan          | Loading paste environment: config:/srv/app/production.ini
ckan          | 2018-04-01 16:36:57,442 CRIT Supervisor running as root (no user in config file)
ckan          | 2018-04-01 16:36:57,443 WARN For [program:ckan-worker], redirect_stderr=true but stderr_logfile has also been set to a filename, the filename has been ignored
ckan          | 2018-04-01 16:36:57,444 INFO Included extra file "/etc/supervisord.d/worker.conf" during parsing
ckan          | Unlinking stale socket /tmp/supervisor.sock
ckan          | 2018-04-01 16:36:57,852 INFO RPC interface 'supervisor' initialized
ckan          | 2018-04-01 16:36:57,853 CRIT Server 'unix_http_server' running without any HTTP authentication checking
ckan          | 2018-04-01 16:36:57,855 INFO supervisord started with pid 24
ckan          | 2018-04-01 16:36:58,859 INFO spawned: 'ckan-worker' with pid 31
ckan          | 2018-04-01 16:36:59,861 INFO success: ckan-worker entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
solr          | 28181 INFO  (qtp1989972246-18) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=0
solr          | 28183 INFO  (qtp1989972246-18) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/select params={q=*:*&rows=1&wt=json} hits=0 status=0 QTime=0
solr          | 28340 INFO  (qtp1989972246-17) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/admin/file params={file=schema.xml} status=0 QTime=70
solr          | 28341 INFO  (qtp1989972246-12) [   x:ckan] o.a.s.c.S.Request [ckan]  webapp=/solr path=/admin/file params={file=schema.xml} status=0 QTime=73
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
ckan          | Traceback (most recent call last):
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
ckan          |     return loadobj(APP, uri, name=name, **kw)
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
ckan          |     return context.create()
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
ckan          |     return self.object_type.invoke(self)
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
ckan          |     return fix_call(context.object, context.global_conf, **context.local_conf)
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
ckan          |     return loadobj(APP, uri, name=name, **kw)
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
ckan          |     return context.create()
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
ckan          |     return self.object_type.invoke(self)
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
ckan          |     return fix_call(context.object, context.global_conf, **context.local_conf)
ckan          |   File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
ckan          |     val = callable(*args, **kw)
ckan          |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 46, in make_app
ckan          |     val = callable(*args, **kw)
ckan          |   File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 46, in make_app
ckan          |         load_environment(conf, app_conf)
ckan          |   File "/srv/app/src/ckan/ckan/config/environment.py", line 99, in load_environment
ckan          | load_environment(conf, app_conf)
ckan          |   File "/srv/app/src/ckan/ckan/config/environment.py", line 99, in load_environment
ckan          |         p.load_all()
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 129, in load_all
ckan          | p.load_all()
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 129, in load_all
ckan          |         unload_all()
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 182, in unload_all
ckan          | unload_all()
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 182, in unload_all
ckan          |         unload(*reversed(_PLUGINS))
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 210, in unload
ckan          |     unload(*reversed(_PLUGINS))
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 210, in unload
ckan          |     plugins_update()
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
ckan          |     plugins_update()
ckan          |   File "/srv/app/src/ckan/ckan/plugins/core.py", line 121, in plugins_update
ckan          |     environment.update_config()
ckan          |   File "/srv/app/src/ckan/ckan/config/environment.py", line 207, in update_config
ckan          |     environment.update_config()
ckan          |   File "/srv/app/src/ckan/ckan/config/environment.py", line 207, in update_config
ckan          |     search.check_solr_schema_version()
ckan          |   File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 306, in check_solr_schema_version
ckan          | search.check_solr_schema_version()
ckan          |   File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 306, in check_solr_schema_version
ckan          |     % (version, ', '.join(SUPPORTED_SCHEMA_VERSIONS)))
ckan          | ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.8. Supported versions are [2.7]
ckan          |     % (version, ', '.join(SUPPORTED_SCHEMA_VERSIONS)))
ckan          | ckan.lib.search.common.SearchError: SOLR schema version not supported: 2.8. Supported versions are [2.7]
ckan          | OOPS ! failed loading app in worker 1 (pid 26) :( trying again...
ckan          | DAMN ! worker 1 (pid: 26) died :( trying respawn ...

**Comment by ccancellieri** [comment]
I've got the same when I switched back to 2.8 (this repo does not have a full backport and change versions in only one ckan doker file is not enough).

Try looking at solr/Dockerfile and fix the version accordingly
