### ISSUE TITLE
ckan did not start

### ISSUE THREAD

**Issue by terchris** [okfn/docker-ckan#6]
Thanks for doing this. A easy dev setup like this is really needed.

I did 
docker-compose build
and 
docker-compose up

But the ckan container did not start.

This is the container log:
```
SRC_EXTENSIONS_DIR=/srv/app/src_extensions
CKAN__PLUGINS=image_view text_view recline_view datastore datapusher envvars repo_info
CKAN_SMTP_USER=user
HOSTNAME=60068fda2634
DEVELOPMENT_MODE=true
CKAN_SMTP_STARTTLS=True
CKAN_REDIS_URL=redis://redis:6379/1
CKAN_DATAPUSHER_URL=http://datapusher:8800
CKAN_SITE_ID=default
CKAN_SQLALCHEMY_URL=postgresql://ckan:ckan@db/ckan
CKAN_SMTP_SERVER=smtp.corporateict.domain:25
GIT_URL=https://github.com/ckan/ckan.git
CKAN__HARVEST__MQ__REDIS_DB=1
CKAN_SYSADMIN_PASSWORD=test
APP_DIR=/srv/app
SRC_DIR=/srv/app/src
PWD=/srv/app
HOME=/root
CKAN_INI=/srv/app/production.ini
CKAN__HARVEST__MQ__HOSTNAME=redis
CKAN_SITE_URL=http://ckan:5000
CKAN__HARVEST__MQ__PORT=6379
CKAN_STORAGE_PATH=/var/lib/ckan
CKAN_SOLR_URL=http://solr:8983/solr/ckan
no_proxy=*.local, 169.254/16
CKAN_DATASTORE_WRITE_URL=postgresql://ckan:ckan@db/datastore
CKAN__HARVEST__MQ__TYPE=redis
CKAN_SYSADMIN_NAME=ckan_admin
CKAN_DATASTORE_READ_URL=postgresql://datastore_ro:datastore@db/datastore
CKAN__STORAGE_PATH=/var/lib/ckan
POSTGRES_PASSWORD=ckan
DATASTORE_READONLY_PASSWORD=datastore
CKAN_SMTP_PASSWORD=pass
SHLVL=1
GIT_BRANCH=ckan-2.7.2
CKAN_SMTP_MAIL_FROM=ckan@localhost
PIP_SRC=/srv/app/src
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CKAN_PORT=5000
CKAN_SYSADMIN_EMAIL=your_email@example.com
_=/bin/printenv
Starting CKAN in development mode
Looking for local extensions to install...
Extension dir contents:
total 8
drwxr-xr-x    3 root     root            96 Jan 26 09:35 .
drwxr-xr-x    1 ckan     root          4096 Jan 26 10:06 ..
-rw-r--r--    1 root     root           378 Jan 26 08:31 README.md
Loading the following plugins: image_view text_view recline_view datastore datapusher envvars repo_info
Edited option ckan.plugins = "image_view text_view recline_view datastore datapusher envvars"->"image_view text_view recline_view datastore datapusher envvars repo_info" (section "app:main")
could not connect to server: Connection refused
Is the server running on host "db" (172.20.0.2) and accepting
TCP/IP connections on port 5432?
2018-01-26T10:08:00.869168900Z 
[prerun] Unable to connect to the database, waiting...
[prerun] Initializing or upgrading db - start
Traceback (most recent call last):
  File "/usr/bin/paster", line 11, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/srv/app/src/ckan/ckan/lib/cli.py", line 333, in command
    self._load_config(cmd!='upgrade')
  File "/srv/app/src/ckan/ckan/lib/cli.py", line 306, in _load_config
    self.site_user = load_config(self.options.config, load_site_user)
  File "/srv/app/src/ckan/ckan/lib/cli.py", line 221, in load_config
    load_environment(conf.global_conf, conf.local_conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 153, in load
    service = _get_service(plugin)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 256, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: repo_info
2018-01-26T10:08:00.869947700Z 
Traceback (most recent call last):
  File "prerun.py", line 185, in <module>
    init_db()
  File "prerun.py", line 89, in init_db
    raise e
subprocess.CalledProcessError: Command '['paster', '--plugin=ckan', 'db', 'init', '-c', '/srv/app/production.ini']' returned non-zero exit status 1
Starting subprocess with file monitor
Traceback (most recent call last):
  File "/usr/bin/paster", line 11, in <module>
    load_entry_point('PasteScript==2.0.2', 'console_scripts', 'paster')()
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 284, in command
    relative_to=base, global_conf=vars)
  File "/usr/lib/python2.7/site-packages/paste/script/serve.py", line 329, in loadapp
    **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 247, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 272, in loadobj
    return context.create()
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 710, in create
    return self.object_type.invoke(self)
  File "/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 146, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/usr/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 46, in make_app
    load_environment(conf, app_conf)
  File "/srv/app/src/ckan/ckan/config/environment.py", line 99, in load_environment
    p.load_all()
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 139, in load_all
    load(*plugins)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 153, in load
    service = _get_service(plugin)
  File "/srv/app/src/ckan/ckan/plugins/core.py", line 256, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: repo_info
```

**Comment by amercader** [comment]
Thanks for trying this out!

Looks like it's trying to load a plugin that is not present (`repo_info`). I was using this as test when developing so not sure why it got stuck there (unless you added it to `.env`). It's definitely not on the latest version.

Are you running the latest master version? Are you sure the images are up to date? Try to rebuild them with

```
docker-compose rm
docker-compose build --no-cache
```

**Comment by gerbyzation** [comment]
`repo_info` was by default in the `.env` file, so if you remove it there it should work fine.

With the merge of #5 `pages` and  `dcat` have snuck in and replaced `repo_info` in the plugin list. 

Suggest we rename the default `.env` configuration to `.env.example` that can be copied and remove `.env` from the repo.

**Comment by terchris** [comment]
Thanks :)
The 
docker-compose rm
docker-compose build --no-cache
docker-compose up

Did the trick. Now It started :)

**Comment by amercader** [comment]
@terchris great! Feel free to report any other issue or feedback.

@gerbyzation yes, dcat and pages were just tests. I think we should remove them from the `.env.example` but leave the lines commented on `ckan/Dockerfile` to show how to install extensions in images.
