### ISSUE TITLE
Standard User not working / new Created User not working

### ISSUE THREAD

**Issue by TimoB2005** [okfn/docker-ckan#97]
Hello,

in my .env file i have that configured:

```
CKAN_SYSADMIN_NAME=ckan_admin
CKAN_SYSADMIN_PASSWORD=adminadmin
CKAN_SYSADMIN_EMAIL=your_email@example.com
```

That credentials are not working. So i get in the container bash and tried to create manually a new user.
Following Command: `ckan -c ckan.ini sysadmin add myusername email=myemail@mail.com`
So CKAN creates a new user with my password.

When i try to login with both User i get this message:

![image](https://user-images.githubusercontent.com/83423736/181453524-918bca63-0c48-4b26-adc7-ac183806acd8.png)

There are no several Errors in the Logs.

Best regards!

**Comment by kosgobakis** [comment]
The issue is when the ckan image runs the start_ckan.sh-> runs the prerun.py script that creates the default admin.
There is a strange issue on the prerun.py, L:80 when it excecutes the eval(connection.read())
`
Traceback (most recent call last):
  File "prerun.py", line 204, in <module>
    check_solr_connection()
  File "prerun.py", line 85, in check_solr_connection
    eval(connection.read())
  File "<string>", line 8, in <module>
NameError: name 'true' is not defined
`

A temporary solution is to comment the prerun.py, L:203
